# Generated by Django 4.2 on 2023-04-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_todo', '0002_alter_userstodolist_on_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstodolist',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
